//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatchMaster
    {
        private long p1;
        private string p2;

        public tblBatchMaster()
        {
            this.tblBatchCourses = new HashSet<tblBatchCourse>();
            this.tblSessionActivities = new HashSet<tblSessionActivity>();
            this.tblStudentAllocations = new HashSet<tblStudentAllocation>();
        }

        public tblBatchMaster(long p1, string p2)
        {
            // TODO: Complete member initialization
            this.BatchId = p1;
            this.BatchName = p2;
        }
    
        public long BatchId { get; set; }
        public string BatchCode { get; set; }
        public string BatchName { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblBatchCourse> tblBatchCourses { get; set; }
        public virtual ICollection<tblSessionActivity> tblSessionActivities { get; set; }
        public virtual ICollection<tblStudentAllocation> tblStudentAllocations { get; set; }
    }
}
