//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBatchCourse
    {
        public long BatchCourseId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblBatchMaster tblBatchMaster { get; set; }
        public virtual tblCourseMaster tblCourseMaster { get; set; }
    }
}
