//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCityMaster
    {
        public tblCityMaster()
        {
            this.tblEmployeeDetails = new HashSet<tblEmployeeDetail>();
            this.tblStudentDetails = new HashSet<tblStudentDetail>();
        }
    
        public long CityId { get; set; }
        public string CityName { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblEmployeeDetail> tblEmployeeDetails { get; set; }
        public virtual ICollection<tblStudentDetail> tblStudentDetails { get; set; }
    }
}
