//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        private long p1;
        private string p2;

        public tblEmployeeDetail()
        {
            this.tblStaffAttendances = new HashSet<tblStaffAttendance>();
            this.tblSubjectEmployeeMappings = new HashSet<tblSubjectEmployeeMapping>();
        }

        public tblEmployeeDetail(long p1, string p2)
        {
            // TODO: Complete member initialization
            this.EmployeeId = p1;
            this.FirstName = p2;
        }
    
        public long EmployeeId { get; set; }
        public string EmployeeCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> Sex { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<long> CityId { get; set; }
        public string ResiContacts { get; set; }
        public string Contacts { get; set; }
        public string Email { get; set; }
        public byte[] Dpic { get; set; }
        public string Designation { get; set; }
        public Nullable<long> isActive { get; set; }
        public string Qualificaton { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblCityMaster tblCityMaster { get; set; }
        public virtual tblGenderMaster tblGenderMaster { get; set; }
        public virtual ICollection<tblStaffAttendance> tblStaffAttendances { get; set; }
        public virtual ICollection<tblSubjectEmployeeMapping> tblSubjectEmployeeMappings { get; set; }
    }
}
