//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeesDetail
    {
        public long RecordId { get; set; }
        public string FeeReceiptNo { get; set; }
        public Nullable<long> AllocationId { get; set; }
        public Nullable<decimal> AmountToBePaid { get; set; }
        public Nullable<decimal> AmountPaid { get; set; }
        public Nullable<decimal> ActualFees { get; set; }
        public Nullable<decimal> ServiceTax { get; set; }
        public Nullable<decimal> OtherTax { get; set; }
        public Nullable<System.DateTime> PaidTimeStamp { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> Advance { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblStudentAllocation tblStudentAllocation { get; set; }
    }
}
