//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFeeStructure
    {
        public long FeeStructId { get; set; }
        public Nullable<long> AllocationId { get; set; }
        public Nullable<int> InstallmentNo { get; set; }
        public Nullable<decimal> InstallmentAmount { get; set; }
        public Nullable<System.DateTime> InstallmentDate { get; set; }
        public Nullable<decimal> AmountRemaining { get; set; }
        public string PaidStatus { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblStudentAllocation tblStudentAllocation { get; set; }
    }
}
