//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocationMaster
    {
        public tblLocationMaster()
        {
            this.tblLocationRoomMappings = new HashSet<tblLocationRoomMapping>();
            this.tblSessionActivities = new HashSet<tblSessionActivity>();
        }
    
        public long LocationId { get; set; }
        public string LocationCode { get; set; }
        public string LocationName { get; set; }
        public string LocationDescription { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblLocationRoomMapping> tblLocationRoomMappings { get; set; }
        public virtual ICollection<tblSessionActivity> tblSessionActivities { get; set; }
    }
}
