//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLocationRoomMapping
    {
        public long LocationRoomId { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblLocationMaster tblLocationMaster { get; set; }
        public virtual tblRoomMaster tblRoomMaster { get; set; }
    }
}
