//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubjectEmployeeMapping
    {
        public long SubjectMapId { get; set; }
        public Nullable<long> EmployeeId { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public Nullable<long> isActvie { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblEmployeeDetail tblEmployeeDetail { get; set; }
        public virtual tblSubjectMaster tblSubjectMaster { get; set; }
    }
}
