//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSessionActivity
    {
        public tblSessionActivity()
        {
            this.tblStaffAttendances = new HashSet<tblStaffAttendance>();
            this.tblStudentAttendances = new HashSet<tblStudentAttendance>();
        }
    
        public long SessionActivityId { get; set; }
        public Nullable<long> SessionId { get; set; }
        public Nullable<long> TaskId { get; set; }
        public Nullable<System.DateTime> SessionDate { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string SessionDuration { get; set; }
        public Nullable<long> LocationId { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CourseId { get; set; }
        public Nullable<long> BatchId { get; set; }
        public Nullable<long> SubjectId { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<long> isCompleted { get; set; }
        public Nullable<long> ActivityStatus { get; set; }
        public Nullable<long> AttendanceRecorded { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tblBatchMaster tblBatchMaster { get; set; }
        public virtual tblCourseMaster tblCourseMaster { get; set; }
        public virtual tblLocationMaster tblLocationMaster { get; set; }
        public virtual tblRoomMaster tblRoomMaster { get; set; }
        public virtual tblSessionMaster tblSessionMaster { get; set; }
        public virtual tblTaskMaster tblTaskMaster { get; set; }
        public virtual ICollection<tblStaffAttendance> tblStaffAttendances { get; set; }
        public virtual ICollection<tblStudentAttendance> tblStudentAttendances { get; set; }
    }
}
