//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSessionMaster
    {
        public tblSessionMaster()
        {
            this.tblSessionActivities = new HashSet<tblSessionActivity>();
        }
    
        public long SessionId { get; set; }
        public string SessionCode { get; set; }
        public Nullable<long> SessionOwnerId { get; set; }
        public string SessionDescription { get; set; }
        public Nullable<int> SessionTime { get; set; }
        public Nullable<long> SessionOccurances { get; set; }
        public Nullable<long> isActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual ICollection<tblSessionActivity> tblSessionActivities { get; set; }
    }
}
